version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: url-shortener-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=urlshortener
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - url-shortener-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/urlshortener --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Analytics Service
  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/urlshortener
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - url-shortener-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redirector Service
  redirector-service:
    build:
      context: ./redirector-service
      dockerfile: Dockerfile
    container_name: redirector-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/urlshortener
      - ANALYTICS_SERVICE_URL=http://analytics-service:3002
      - BASE_URL=http://localhost:3001
    depends_on:
      mongodb:
        condition: service_healthy
      analytics-service:
        condition: service_healthy
    networks:
      - url-shortener-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Networks
networks:
  url-shortener-network:
    driver: bridge
    name: url-shortener-network

# Volumes
volumes:
  mongodb_data:
    driver: local
    name: url-shortener-mongodb-data
  mongodb_config:
    driver: local
    name: url-shortener-mongodb-config