# k8s/analytics-deployment.yaml
# Analytics Service Kubernetes Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: url-shortener
  labels:
    app: analytics-service
    tier: backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: analytics-service
        tier: backend
        version: v1
    spec:
      containers:
      - name: analytics-service
        image: ghcr.io/priya00300/analytics-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-uri
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3

---
# Analytics Service - Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: url-shortener
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  sessionAffinity: None
